window.MENU_ITEMS = {
  cakes: [
    {
      id: "bento-2layer",
      name: "Bento 2Layer",
      price: 450,
      flavors: ["Vanilla", "Chocolate", "Red velvet", "Custom"],
    },
    {
      id: "bento-cuppies",
      name: "Bento 2Layer + 5 Cuppies",
      price: 600,
      flavors: ["Vanilla", "Chocolate", "Mixed", "Custom"],
    },
    {
      id: "small-6inch",
      name: "Small 6inch Cake",
      price: 750,
      flavors: ["Vanilla", "Chocolate", "Red velvet", "Custom"],
    },
    {
      id: "medium-7inch",
      name: "Medium 7inch Cake",
      price: 950,
      flavors: ["Vanilla", "Chocolate", "Red velvet", "Custom"],
    },
    {
      id: "large-8inch",
      name: "Large 8inch Cake",
      price: 1150,
      flavors: ["Vanilla", "Chocolate", "Red velvet", "Custom"],
    },
    {
      id: "two-layers",
      name: "2 Layers (5 and 7inch)",
      price: 1600,
      flavors: ["Vanilla", "Chocolate", "Mixed", "Custom"],
    },
    {
      id: "gloss-picture",
      name: "Gloss Picture",
      price: 100,
      flavors: ["Add-on"],
    },
    {
      id: "edible-picture",
      name: "Edible Picture",
      price: 150,
      flavors: ["Add-on"],
    },
    {
      id: "custom-topper",
      name: "Custom Topper",
      price: 150,
      flavors: ["Add-on"],
    },
    {
      id: "chocolates",
      name: "Chocolates",
      price: 350,
      flavors: ["Assorted"],
    },
    {
      id: "dummy-3tier",
      name: "Dummy 3 tier Cake",
      price: 1500,
      flavors: ["Display / props"],
    },
  ],
  "finger-foods": [
    {
      id: "samosa-frozen",
      name: "Samosa (Frozen ×5)",
      price: 45,
      flavors: ["Frozen pack"],
    },
    {
      id: "samosa-cooked",
      name: "Samosa (Cooked ×10)",
      price: 100,
      flavors: ["Cooked pack"],
    },
    {
      id: "spring-roll-frozen",
      name: "Spring Roll (Frozen ×5)",
      price: 50,
      flavors: ["Frozen pack"],
    },
    {
      id: "spring-roll-cooked",
      name: "Spring Roll (Cooked ×10)",
      price: 120,
      flavors: ["Cooked pack"],
    },
    {
      id: "sausage-roll-frozen",
      name: "Sausage roll (Frozen ×5)",
      price: 60,
      flavors: ["Frozen pack"],
    },
    {
      id: "sausage-roll-cooked",
      name: "Sausage roll (Cooked ×10)",
      price: 150,
      flavors: ["Cooked pack"],
    },
    {
      id: "russian-roll-frozen",
      name: "Russian Roll (Frozen ×5)",
      price: 60,
      flavors: ["Frozen pack"],
    },
    {
      id: "russian-roll-cooked",
      name: "Russian Roll (Cooked ×10)",
      price: 150,
      flavors: ["Cooked pack"],
    },
    {
      id: "mini-pizza-frozen",
      name: "Mini Pizza's (Frozen ×5)",
      price: 100,
      flavors: ["Frozen pack"],
    },
    {
      id: "mini-pizza-cooked",
      name: "Mini Pizza's (Cooked ×10)",
      price: 250,
      flavors: ["Cooked pack"],
    },
    {
      id: "pie-frozen",
      name: "Pie (Frozen ×5)",
      price: 125,
      flavors: ["Frozen pack"],
    },
    {
      id: "pie-cooked",
      name: "Pie (Cooked ×10)",
      price: 300,
      flavors: ["Cooked pack"],
    },
  ],
};
